title: Akul Bajaj - Data Science Portfolio 
logo: "/images/Akul Bajaj (1).jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  description: > 
  Data Scientist | Machine Learning Enthusiast | Storyteller
  <br><br>
  Welcome to my data-driven universe! With an unwavering commitment to uncovering insights, I fuse the art of storytelling with the precision of machine learning. My journey began with a Master's degree and culminated in three years of hands-on exploration, where I've honed skills that drive impactful decisions. As a former data scientist intern at the Metropolitan Transportation Commission, I have navigated the dynamic terrain of real-world data challenges. My passion thrives at the intersection of deep learning, NLP, and computer vision, where I relish transforming abstract algorithms into tangible solutions. Let's embark on a data-driven adventure together.
  <br><br>
  <a href="https://www.linkedin.com/in/akul-bajaj/">Connect with me on LinkedIn</a>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
